/********************************************************************************
 * Copyright (c) 2026 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

@startuml pastey_root_causes

!include fta_metamodel.puml

$TopEvent("Wrong or missing identifier", "PasteyFailureModes.CompilationErrors")

$OrGate("Gate1", "TopEvent")

$BasicEvent("paste! used in invalid syntax position", "PasteyFailureModes.InvalidTokenPlacement", "Gate1")

$BasicEvent("Compilation error due to empty token stream", "PasteyAoU.PasteyRustCompilerCertified", "Gate1")

$BasicEvent("Unsupported modifier generate compilation error", "PasteyAoU.PasteyUsedInValidSyntaxPositions", "Gate1")
@enduml
